api-trading-env: ENC[AES256_GCM,data:icbO4zRmuoTYiNZPzWPQseN/OkfC3FMLMYaYtfTH3BWa+NsfYYSareLuhEj0+LceVpVmlpTkCit+2k+mkXvJVS14RNfkBF95Hgluc/zLitC++tlCk3jnuLk/P+TAon5DodAo5HZFhykOiWj6ZN7I+6gHsY6rzRpfWAk7kihCVBLJ48GasMwcYzHUEc81RW12fI+oSCvTbMbHFdTLMObnGq6sCUHpzMMPjM+TQ3euby6nNToGACjRKxFqCrkF8Jy1aVbqLW8xew5rxlLEkFfacvClvjK+/v9UFaBOR4lq99EZygrOLKfDLzIll+m5PhUaqnpeTMqVY/2W3TKCFGSLqS3b8c6abB9C7fPdqrlUae/kNSwnZlPnbm3k+XdT02DQLNfrfaySuXT+fgeEWUq8JTU03NGA7esYYVeEyVX0kApiHDgsvvFMUDBfhsnVFvJFa8X3kWrB0sNJYnKsNFrBtwmM+SVDhI8B,iv:YsJlzGWUaKD0MND6Hydymq5B8mfHyKb5mIU3bwM5rAk=,tag:GjbNoPvLNLw5A/Zziqn6lw==,type:str]
bot-trading-env: ENC[AES256_GCM,data:DFB7v3AW4pOWIke+DJXlf40sC6ajteWK8R6nkv/cD+9VSg==,iv:SsOH50CB5yw9uDNxYYUNKvjHceZNWHJE/uDw5s0fBFA=,tag:XDucMcZSEmFvpDpcMzTbiQ==,type:str]
web-trading-env: ENC[AES256_GCM,data:Ku8BBJEmc9LmgPD2X0hLBfx9dS4YCubHaK7Cjg==,iv:hqq4yBwZN8XgaFf6pkcZ8fAc+xV7hFRQld1n+XRJa8A=,tag:vWZkeD4TunE2XNcI5xsPhA==,type:str]
sops:
    age:
        - recipient: age1qe3jac9hdy5mlj5n3vp64gqc74euv4a8aazpwne447ytyah7xuwse026he
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYnE5WHl0c0crVmZiQWJH
            Tnl4YmJUSW96TEdQVGQ5dVFBblBCMVN5dUdZCm1pRlhzSlpEdmQzMVBDRzgvOVNp
            NjA3d3llSm9yY3M4czJoTzYyb3FYeXMKLS0tICtabVFSdjRvbGxvZnY0ck14NVU0
            YW9TNnNtT1M5UnJUZmRLd2poY1BNdmcK7wLUuw8k6glT0ZuD/mgFzaUl+9M1GRxy
            1VPz4i9KKsTz4LkvLlu2EMWVvjKwEEW/r8o77q+ZSqs55jcanLSwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T11:47:00Z"
    mac: ENC[AES256_GCM,data:vJmy051nXUj0CiBDKjnYV3YcWCZeqlc1tZgwr5u/CAf4yh1D6kBfIZNxY8AOK2j+4VfdEWdyAIKmgWaXDXc1zZBHRniNqFjl83IQorQLs0jvFn8HiWnAzj+aHI4PKlEo5So4lYXF1qw85XqFeQjwD3Y69NtnwyG9EfphSmHEQYI=,iv:rngo+h1dvtyLXcQSCG87TV0hwjW9X3WtEqcP0JdR+as=,tag:okoAK4U6s2wTlx8oAkppcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
