api-env: ENC[AES256_GCM,data:HsArfRLxpoXwCxMX6+IDFRdz9l8xkyFyon1KDfwfLLMMNaMNxgzqxBR4o89KttsLyYILvHnGyhoNqpusCMSGgFUgJpDev5mpKLb/YLK+JLtWjsIo5UnnMu9CyT3icn9myMEmGjS9IDYO9WZ0OycQ5wbVSEKT3AAtPoWZe3n55W67iYVT7Wx0Ow8lRAe2ByVuf1SGMbo/jne7exW/f3BSHuD8fLzEjBhseDHn62wK9y0ay1umTgNgzcd0B5TGb9cHGHsydLpnYJIDBGolkBUZP5Omcyt5Yj5G9VZLUlA5QU8LWk0ftZ1Q/PMYGAeBIhYMMYsZQL7xi92CTFmv03XrxklbxNTqoYVr1wrF+y/Qlz403P6GVIp2ntHKVGZxaNWBl1IpSyhRjEkUn1/TK4v/xhUoXVMLHq5okbTduK2kQGrJHJxZwTTWmR29jHO/XDIoG+nrpa3hbSqeHrFTavGPgNQxIbGQcg6l6xUplBfeMj2CYCw=,iv:BeFgAiFrupdl5hOJ+fO2pEdj9SUgxPNgoteIRD8iIVw=,tag:x1AVh71HK6CQVFZlK2FmIA==,type:str]
sops:
    age:
        - recipient: age1qe3jac9hdy5mlj5n3vp64gqc74euv4a8aazpwne447ytyah7xuwse026he
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYnE5WHl0c0crVmZiQWJH
            Tnl4YmJUSW96TEdQVGQ5dVFBblBCMVN5dUdZCm1pRlhzSlpEdmQzMVBDRzgvOVNp
            NjA3d3llSm9yY3M4czJoTzYyb3FYeXMKLS0tICtabVFSdjRvbGxvZnY0ck14NVU0
            YW9TNnNtT1M5UnJUZmRLd2poY1BNdmcK7wLUuw8k6glT0ZuD/mgFzaUl+9M1GRxy
            1VPz4i9KKsTz4LkvLlu2EMWVvjKwEEW/r8o77q+ZSqs55jcanLSwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T00:37:21Z"
    mac: ENC[AES256_GCM,data:U1F2z66Bs6kRhpqe+zflvlfEYgYtH8CmF4eY0nEpQugq+mXDjHCUfn9l2+KzpL0eGHMrzgrK46/y53Jc4hB4535xioEi4ppXIP0/KeGBInyCR+Oqf0QJyBKIvd2ieuWUZZC/BYkUthFqfk/tfdA1qe5D3de8jQnohdfzCyK30l4=,iv:LQpzIUx2fLuDunRLBYBhtOzNxdeZ/CmSObLpXN9Oio0=,tag:GeE5Xnw4EJQxRWxY+ShJow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
