api-env: ENC[AES256_GCM,data:GDpD/LuHg3XBPUJxEBl7QRwnp7EBG/+vtK9dmuUVbUIze2NXSH9zRfJ8sswVOue9HUWiAqUlmVyNa67yK4No3tZIc8d32/ABIWTQCS9vDgTijy5Q8D6a5sC3heMICo+m2IxfcsXVKX4UE1I8OONpwspFS+wclfTyiHUk1/Bi3gCE/HlJ1BQR2oXv+hqcQc5m9r8pCndJ9caf5OcuT1+nN5yIcEAn2XlKh9MZcZzrnHPdr1SJkMdLV0hNhQTD6ewr8jFx1eQiIL3+qLpvbmuMsE+jXDdPz5wE3nnIeu0PcPLObZEwKnRTaQtnCEk3NNNrFJNyMB+jogTkTFU9fXQgD4DB0Pp6uO1PyVOvldmhp8nPbbDSsXfvnY+6DmUXdeQhi76wkI4yhq/dsDcTDZya46ViFz6j0hz9YrHBpf9/bc33FKcoMlN2WXbBdwKOCi0J+KeWvpSg23W60QrsKeqg6g==,iv:BXBK3RDEFi+nZ/PauHAybEZLsGkW+5bvTX1nVAhD8JU=,tag:6ArmRjN4BlSmx5g0EyVVUg==,type:str]
sops:
    age:
        - recipient: age1qe3jac9hdy5mlj5n3vp64gqc74euv4a8aazpwne447ytyah7xuwse026he
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYnE5WHl0c0crVmZiQWJH
            Tnl4YmJUSW96TEdQVGQ5dVFBblBCMVN5dUdZCm1pRlhzSlpEdmQzMVBDRzgvOVNp
            NjA3d3llSm9yY3M4czJoTzYyb3FYeXMKLS0tICtabVFSdjRvbGxvZnY0ck14NVU0
            YW9TNnNtT1M5UnJUZmRLd2poY1BNdmcK7wLUuw8k6glT0ZuD/mgFzaUl+9M1GRxy
            1VPz4i9KKsTz4LkvLlu2EMWVvjKwEEW/r8o77q+ZSqs55jcanLSwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T07:33:37Z"
    mac: ENC[AES256_GCM,data:YNEw36Axz18wSKT6W0k7x+nBl9V/ZGBbDRtOzUEn8yk/KD4YHC7qu/ABkwDObW+0BP3TRW36XTbRrwDih3K6Q2qfkL1I/k0QmJf3d6ZifAkAizMJrnn8t0Eo2Vu2PTt4+KZHLstuun8QCGjpms/FKma15U+m03OQMLVhXN5AaaE=,iv:4oycbFO7yz1Fx8rp2UsxBNhap8UUU4kl2jxrlhEzPZE=,tag:ob1ps2rxHzpqaDASZbnxHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
