api-env: ENC[AES256_GCM,data:gQiCUT6UMnpFIue4hw7G6O0dhhlnNbLn0Ok5N/a6T2M0bQPHwhInalabfEm4MD+bcrnMs2KEDBTokL9DAMFq3NWO9EPNJ5jjRrd2O0h1xK0vvtHWRkA4Jvx2gU/lY1FOHjYuWvxuRy/aeiqkSlOnS/NvsSJ635c7iWUcrFAoPokoTkFyxMxhGCWMi3kO3vIeZ44UCiAiMFcafGQKcLLR294e7W1q7RcadLi63c7kS13EdAWmRTYSEMMQy3/HPwqSJ7FMaGKLFelkrFyehc2eohaiUqTOy3NeBmuxuFQoM0Dx9nQyTbAsAXfdDXGCfRI7+Fkamp22dD3avDUcEmmrw5SS2q8=,iv:gjvmPI3wNLDQi9BBpXUmWpD7YjjjNYQTotNQ7OdfVxk=,tag:pAdycG+wfeXS7y9sXtyPpg==,type:str]
sops:
    age:
        - recipient: age1qe3jac9hdy5mlj5n3vp64gqc74euv4a8aazpwne447ytyah7xuwse026he
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYnE5WHl0c0crVmZiQWJH
            Tnl4YmJUSW96TEdQVGQ5dVFBblBCMVN5dUdZCm1pRlhzSlpEdmQzMVBDRzgvOVNp
            NjA3d3llSm9yY3M4czJoTzYyb3FYeXMKLS0tICtabVFSdjRvbGxvZnY0ck14NVU0
            YW9TNnNtT1M5UnJUZmRLd2poY1BNdmcK7wLUuw8k6glT0ZuD/mgFzaUl+9M1GRxy
            1VPz4i9KKsTz4LkvLlu2EMWVvjKwEEW/r8o77q+ZSqs55jcanLSwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:57:25Z"
    mac: ENC[AES256_GCM,data:27G6xpG2MMa5xS6J1wO/DLLHlnZCQgRg/2Ma8lR0lEsrmYE9tGRVb5pJKsUZ/AUDS/5HB6cYmeLwyaLi3cYSAtqRbR2rRAKu26BsXVxv3IvDjMh9s/RRhUYHYqjZZITFcWzMth6x3F1n8hgWQl6AAXax1vEdxwA81OI0Cd5qWew=,iv:IpqiFrQXBqpVFysk8lCbhbxGr09KVTufAHiy6DXfmL4=,tag:HtYqom/M+TSxQTsKyg9IQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
