api-trading-env: ENC[AES256_GCM,data:7kxQcGM4HjGs1F+QgRFeVULZt7dBd+Y41GUrdv0ZZcDUkeqaERkZZXQAHcjEkoRTeXI+agglcDigwwpP+Xgp+SBOsPsfmF5OWvFpTgYpuymo5JGtaw==,iv:NWrs5PdWSPkoNu1zHu6N+MP8ulXT0k+qmtTLV7jkcmg=,tag:pT1z87te+V3gNpxsfZbtjA==,type:str]
sops:
    age:
        - recipient: age1qe3jac9hdy5mlj5n3vp64gqc74euv4a8aazpwne447ytyah7xuwse026he
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYnE5WHl0c0crVmZiQWJH
            Tnl4YmJUSW96TEdQVGQ5dVFBblBCMVN5dUdZCm1pRlhzSlpEdmQzMVBDRzgvOVNp
            NjA3d3llSm9yY3M4czJoTzYyb3FYeXMKLS0tICtabVFSdjRvbGxvZnY0ck14NVU0
            YW9TNnNtT1M5UnJUZmRLd2poY1BNdmcK7wLUuw8k6glT0ZuD/mgFzaUl+9M1GRxy
            1VPz4i9KKsTz4LkvLlu2EMWVvjKwEEW/r8o77q+ZSqs55jcanLSwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T08:26:36Z"
    mac: ENC[AES256_GCM,data:v8mnNENXHanwW7/VpWHGsVm/avPJ01C35uhUhdpZGaVlrJaiZrcoZs//Tk+KIESr37T9bzbAAfpp0Q7bjaLLolmvZ25PiMnXnLFrLj45B5JhSm25AnvU0+bJ2eKksBsmOTaJo7CJj52xVTqBqAzgPPCcp23TbLkEoS5K0rqsdis=,iv:8cTJI8l+ThUp2n+CMgMQb26yGc9akdipgIEXxrKbpt8=,tag:Kghj7GHXcy3xcnSm35hNlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
