DATABASE_URL: ENC[AES256_GCM,data:ZrZ2fZeX9nwDzz8c0gsIsLErFuicb9stkJKV4zL0PUGJFugxKsPF4GakiiW4qEc6IPa6lWc=,iv:PtiGdqfG3Ajm5XQhp2YDtdsLwlbWFj+0yjMoi6AyEME=,tag:i7SKiZ0Sv2bGBXeHy/DGIQ==,type:str]
JWT_LOGIN_SECRET: ENC[AES256_GCM,data:h/Y0BgMqk6nwLcAJ,iv:Dw3b+K6rxIoK/VeWXg6AjBw2MWOj0thAABza36OeD1o=,tag:FMSXz5aKYD/+3VYBaxcoMA==,type:str]
JWT_AUTH_SECRET: ENC[AES256_GCM,data:rod2kNRIQtsKyAY=,iv:6+bHP9+l82kMjc1BqQlZw41C2FlvRpdkSkCCY6NP8to=,tag:OXKNWfgh4k7f+6qImGK1Xg==,type:str]
JWT_EXP: ENC[AES256_GCM,data:og==,iv:tH2bWamlEx6RczKGRN8lFbqhbQE9CZbRkOqzN2ZAnB8=,tag:VVB4GbiKJ9Y++X7Lb9uUKQ==,type:str]
USERNAME: ENC[AES256_GCM,data:0sHx+wngcMdABtVoeR56,iv:xS1LdfQJq0RiC4zEnhR6PDZxLkjozwBioBuL4mONvH4=,tag:SekO70tkLaUbnHYJW2PQhg==,type:str]
PASSWORD: ENC[AES256_GCM,data:3Di9tNT9jqre7e0bUU8HGXadhfHSMqXNRUsZZQ==,iv:H8dq3Xo4crAkubPHBcHYBXYcFICcqTsz9MbbdjW/9yE=,tag:/hcfwKKFS0O6QgQVwus3xQ==,type:str]
PRODUCTION: ENC[AES256_GCM,data:2Tfngg==,iv:sNw+V3BNF6XzFVMKuDOyFatVtAQARZD6ire5tGifwH8=,tag:hn1hlKNnGwLhcAfZwTrQsQ==,type:str]
OTP_SECRET: ENC[AES256_GCM,data:3v+GUZ9ZOUy2CpMayiLbkJw1L1ZxlDaPHeWlTG+GSIU=,iv:rRCi7q2G//46VwRIudIHE9k7DiPCR8nLi0A186dKA6k=,tag:qDN19/i4DNORnyLBOmX4NQ==,type:str]
sops:
    age:
        - recipient: age1qe3jac9hdy5mlj5n3vp64gqc74euv4a8aazpwne447ytyah7xuwse026he
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYnE5WHl0c0crVmZiQWJH
            Tnl4YmJUSW96TEdQVGQ5dVFBblBCMVN5dUdZCm1pRlhzSlpEdmQzMVBDRzgvOVNp
            NjA3d3llSm9yY3M4czJoTzYyb3FYeXMKLS0tICtabVFSdjRvbGxvZnY0ck14NVU0
            YW9TNnNtT1M5UnJUZmRLd2poY1BNdmcK7wLUuw8k6glT0ZuD/mgFzaUl+9M1GRxy
            1VPz4i9KKsTz4LkvLlu2EMWVvjKwEEW/r8o77q+ZSqs55jcanLSwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T13:38:33Z"
    mac: ENC[AES256_GCM,data:fNnbBnDfhzoS6OyZEZeQ/C7uwSqCVcnvBt519+M5PlDDImFcaFLPY0soSjONZ0/DPri2mFPH4VHXbF5/SpJ95OB1auV4BZzSVmr5ieB7oeXLR9G3Cw7x0cIi4sVELQy+OjVZhrXzMw/8KYs60qFukB8KN3VTb3DKG0jUVDJug7s=,iv:JXA6SLUi1mdBLbWjgF4Ya4rSf2tfQQBkw/CsyWzZyXo=,tag:mXiTH2v9aTCaWld7cHezqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
