api-env: ENC[AES256_GCM,data:5DmkWw1vWqW8iMOkm5IGaUA5wO5wOsPItwVXFgePG4yVY3WfNZXjAiu0YhYDYzDlWTVhdZxzS2tEoScYqC86HJ6Oc+rdaTSIuNEdnbPZvXZhHX6H3+zJxz4QjQz/wTHuNsibeK/BWZABvzZt7WH3pKRDcEXHM1KJRb60BqWhgAGY/xW7qMwiAWPvMHT+dwUO9yWwG9Qwmhu4LWQ1Ru7RlCytAio+wb+MnnRKEUNKWfiPpZghovQG1EUJ6uqFBnGDjPSt/J0L8s31wJq4ecbKhJHUQZDASggxPKEkhwlWzc4/10gFbEObacsxzj47KiGcCmud5U9QF95uLcgnDeHJgIjcSWrSWYyfZ/jhj9z0iDALgR+8Z+UQ0ylK3+BqjaAwn5S0y4Hdo8tTFHPCqOnUTyOSoifM+l5IojU=,iv:q4B8NvdUNiDcAofNxN1M8/gYMXo9mA7vz5yH7dc9p2k=,tag:ro+WTgbwLh/J7Zw+fkdaLw==,type:str]
sops:
    age:
        - recipient: age1qe3jac9hdy5mlj5n3vp64gqc74euv4a8aazpwne447ytyah7xuwse026he
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYnE5WHl0c0crVmZiQWJH
            Tnl4YmJUSW96TEdQVGQ5dVFBblBCMVN5dUdZCm1pRlhzSlpEdmQzMVBDRzgvOVNp
            NjA3d3llSm9yY3M4czJoTzYyb3FYeXMKLS0tICtabVFSdjRvbGxvZnY0ck14NVU0
            YW9TNnNtT1M5UnJUZmRLd2poY1BNdmcK7wLUuw8k6glT0ZuD/mgFzaUl+9M1GRxy
            1VPz4i9KKsTz4LkvLlu2EMWVvjKwEEW/r8o77q+ZSqs55jcanLSwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T05:52:55Z"
    mac: ENC[AES256_GCM,data:GPlcvRs7SFO3bKTx6cJFFGM+AJ/9KBVUtLsrClbc32XkGEco4hRs1OkhvgjON0CC/+qpmyPlIwIjV8SPRlyD28YAbyIFvcRHo84shc/J7a6WkivsSZ05mcvDbF0Z/Yy6UHN/LPyKSHYjk7wuPo501Ly96xxSwcV9TQCUo3L/tYc=,iv:7EC09EoqG25OcZJVLgKXHg9nTMe/r8JP2dlhsCR5vcc=,tag:y757i8VYEiav1aWhCHBUWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
